"""
Public API of the domain package.

All names that were previously importable from ``codex_metrics.domain`` (the
old monolithic module) are re-exported here so that existing imports continue
to work without modification.
"""

from codex_metrics.domain.aggregation import (
    aggregate_chain_costs,
    aggregate_chain_model,
    aggregate_chain_timestamps,
    aggregate_chain_token_component,
    aggregate_chain_tokens,
    append_missing_attempt_entries,
    apply_attempt_usage_deltas,
    apply_goal_updates,
    build_attempt_entry,
    build_effective_goal_record,
    build_effective_goals,
    build_merged_notes,
    build_model_summary,
    close_open_attempt_entry,
    close_previous_open_attempt,
    combine_optional_cost,
    combine_optional_tokens,
    compute_entry_summary,
    compute_numeric_delta,
    compute_summary_block,
    create_goal_record,
    default_metrics,
    empty_summary_block,
    ensure_goal_type_update_allowed,
    finalize_goal_update,
    get_closed_records,
    get_failed_records,
    get_goal_entries,
    get_successful_records,
    get_task,
    get_task_index,
    load_metrics,
    normalize_legacy_metrics_data,
    recompute_summary,
    refresh_goal_model_summary,
    resolve_linked_task_reference,
    round_usd,
    sum_known_numeric_values,
    sync_goal_attempt_entries,
    trim_excess_attempt_entries,
    update_latest_attempt_entry,
)
from codex_metrics.domain.ids import next_entry_id, next_goal_id
from codex_metrics.domain.models import (
    ALLOWED_FAILURE_REASONS,
    ALLOWED_RESULT_FITS,
    ALLOWED_STATUSES,
    ALLOWED_TASK_TYPES,
    AttemptEntryRecord,
    EffectiveGoalRecord,
    GoalRecord,
    StatusRecordT,
)
from codex_metrics.domain.serde import (
    effective_goal_to_dict,
    entry_from_dict,
    entry_to_dict,
    goal_from_dict,
    goal_to_dict,
)
from codex_metrics.domain.time_utils import (
    choose_earliest_timestamp,
    choose_latest_timestamp,
    now_utc_datetime,
    now_utc_iso,
    parse_iso_datetime,
    parse_iso_datetime_flexible,
)
from codex_metrics.domain.validation import (
    build_goal_chain,
    validate_agent_name,
    validate_entry_business_rules,
    validate_entry_record,
    validate_failure_reason,
    validate_goal_entries,
    validate_goal_record,
    validate_goal_supersession_graph,
    validate_metrics_data,
    validate_model_name,
    validate_non_negative_float,
    validate_non_negative_int,
    validate_result_fit,
    validate_status,
    validate_task_business_rules,
    validate_task_type,
    validate_token_breakdown_consistency,
)

__all__ = [
    # models
    "ALLOWED_FAILURE_REASONS",
    "ALLOWED_RESULT_FITS",
    "ALLOWED_STATUSES",
    "ALLOWED_TASK_TYPES",
    "AttemptEntryRecord",
    "EffectiveGoalRecord",
    "GoalRecord",
    "StatusRecordT",
    # time_utils
    "choose_earliest_timestamp",
    "choose_latest_timestamp",
    "now_utc_datetime",
    "now_utc_iso",
    "parse_iso_datetime",
    "parse_iso_datetime_flexible",
    # ids
    "next_entry_id",
    "next_goal_id",
    # serde
    "effective_goal_to_dict",
    "entry_from_dict",
    "entry_to_dict",
    "goal_from_dict",
    "goal_to_dict",
    # validation
    "build_goal_chain",
    "validate_agent_name",
    "validate_entry_business_rules",
    "validate_entry_record",
    "validate_failure_reason",
    "validate_goal_entries",
    "validate_goal_record",
    "validate_goal_supersession_graph",
    "validate_metrics_data",
    "validate_model_name",
    "validate_non_negative_float",
    "validate_non_negative_int",
    "validate_result_fit",
    "validate_status",
    "validate_task_business_rules",
    "validate_task_type",
    "validate_token_breakdown_consistency",
    # aggregation
    "append_missing_attempt_entries",
    "apply_attempt_usage_deltas",
    "apply_goal_updates",
    "build_attempt_entry",
    "build_effective_goal_record",
    "build_effective_goals",
    "build_merged_notes",
    "build_model_summary",
    "close_open_attempt_entry",
    "close_previous_open_attempt",
    "combine_optional_cost",
    "combine_optional_tokens",
    "compute_entry_summary",
    "compute_numeric_delta",
    "compute_summary_block",
    "create_goal_record",
    "default_metrics",
    "empty_summary_block",
    "ensure_goal_type_update_allowed",
    "finalize_goal_update",
    "get_closed_records",
    "get_failed_records",
    "get_goal_entries",
    "get_successful_records",
    "get_task",
    "get_task_index",
    "load_metrics",
    "normalize_legacy_metrics_data",
    "recompute_summary",
    "refresh_goal_model_summary",
    "resolve_linked_task_reference",
    "round_usd",
    "sum_known_numeric_values",
    "sync_goal_attempt_entries",
    "trim_excess_attempt_entries",
    "update_latest_attempt_entry",
    "aggregate_chain_costs",
    "aggregate_chain_model",
    "aggregate_chain_timestamps",
    "aggregate_chain_token_component",
    "aggregate_chain_tokens",
]
